[package]
name = "codotaku_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9"
itertools = { version = "0.12.1", default-features = false }
spin = "0.9.8"
volatile = "0.2.6"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
